# Generated by Django 3.2.9 on 2022-01-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20220107_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lahgs',
            new_name='langs',
        ),
    ]
