# Generated by Django 3.2.9 on 2021-12-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='update_timestapp',
            new_name='update_timestamp',
        ),
    ]
